<a href="https://colab.research.google.com/github/DeepPatel21313/CarPricePrediction/blob/main/TensorFlowBeginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["Hello World","Hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'Hi'], shape=(2,), dtype=string)


In [ ]:
tensor_one_d = tf.constant([2,0,-3.], dtype=tf.float32)
casted_tensor_one = tf.cast(tensor_one_d, dtype=tf.int16)
print(casted_tensor_one)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int16)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [3 5 1]
 [1 5 6]
 [2 3 8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 0]
  [3 5 1]]

 [[1 2 0]
  [3 5 1]]

 [[1 2 0]
  [3 5 1]]

 [[1 2 0]
  [3 5 1]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
eye_tensor =tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,], # it will show 2 5x5 Identity matrices
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [1,3,4] , 5 , name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [5,3]
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [5,3]
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
print(tf.shape(zeros_tensor))

tf.Tensor([5 3], shape=(2,), dtype=int32)


In [ ]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=0.01,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.0097    99.994576]
 [100.00348  100.002335]
 [ 99.98025   99.98808 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[691 310 378 232 131]
 [510 531 849 639 516]
 [667 173  86 512  74]
 [680 467 913 226 654]
 [136 561 860 948 643]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)
tf.Tensor([2 2 1], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)
tf.Tensor([2 2 1], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([1,2,3,4,5,6,7,8])
print(tensor_indexed[1:6:2])

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d[...,0])

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]]
])
print(tensor_three_d[ ... , : , 2])

tf.Tensor(
[[0 1]
 [0 1]
 [0 1]
 [0 1]], shape=(4, 2), dtype=int32)


In [ ]:
x_abs = tf.constant([-2.24 +4.75j])
tf.abs(x_abs)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25167592])>

In [ ]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [ ]:
x_1 = tf.constant([[5,6,7,8,9],], dtype=tf.int32)
x_2 = tf.constant([[2],[3],[4]], dtype=tf.int32)
print(x_1.shape)
print(x_2.shape)
print(tf.multiply(x_1,x_2))

(1, 5)
(3, 1)
tf.Tensor(
[[10 12 14 16 18]
 [15 18 21 24 27]
 [20 24 28 32 36]], shape=(3, 5), dtype=int32)


In [ ]:
B = tf.constant([[2, 20, 30, 3, 6],
                 [3, 11, 16, 1, 8],
                 [14., 45, 23, 5, 27]])
print(tf.math.argmin(B, 1))

tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [ ]:
print(tf.math.reduce_std(
    B , axis=0, keepdims=True, name=None
))

tf.Tensor([[ 5.436502  14.383632   5.715476   1.6329932  9.46338  ]], shape=(1, 5), dtype=float32)


In [ ]:
tf.math.top_k(tensor_two_d, k=2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 1],
       [5, 3],
       [6, 5],
       [8, 3]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [ ]:
x_1 = tf.constant([[1,2,0],[3,5,-1]])
x_2 = tf.constant([[1,2,0],[2,1,1],[3,1,1]])
tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(tf.transpose(x_1))

tf.Tensor(
[[ 1  3]
 [ 2  5]
 [ 0 -1]], shape=(3, 2), dtype=int32)


In [ ]:
x1 = tf.constant([
    [[0,0],
    [0,5]]
])
x2 = tf.constant([
    [[1,0,0],
    [0,0,0]]
])

print(tf.linalg.matmul(x1,x2))

tf.Tensor(
[[[ 7 12  2]
  [18 31  5]]

 [[ 9 12  2]
  [23 31  5]]

 [[ 7 12  2]
  [23 41  5]]

 [[11 12  2]
  [29 33  5]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,1],
    [1,5,6.]], dtype=tf.float32)

In [ ]:
tensor_2d_inverse = tf.linalg.inv(tensor_two_d)

In [ ]:
tensor_2d_inverse@tensor_two_d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00, -1.7881393e-07, -1.1920929e-07],
       [-1.4156103e-07,  1.0000001e+00,  4.4703484e-08],
       [ 5.9604645e-08, -5.9604645e-08,  1.0000000e+00]], dtype=float32)>

In [ ]:
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)

tf.Tensor([9.397966   3.6892838  0.25957716], shape=(3,), dtype=float32)


In [ ]:
import numpy as np
A = np.array([[2,6,5,2],
              [2,-2,2,3],
               [1,5,4,0]
])
B = np.array([[2,9,0,3,0],
              [3,6,8,-2,2],
               [1,3,5,0,1],
                [3,0,2,0,5]])
print(np.matmul(A,B), "\n")
print(np.einsum("ij,jk -> ik",A,B))

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [ ]:
A = np.array([[2,6,5,2,1],
              [2,-2,2,3,1],
               [1,5,4,0,1]
])
B = np.array([[2,9,0,3,0],
              [3,6,8,-2,2],
               [1,3,5,0,1]])
# print(np.matmul(A,B), "\n")
print(np.einsum("ij,ij -> ij",A,B))
# print(A*B)

[[  4  54   0   6   0]
 [  6 -12  16  -6   2]
 [  1  15  20   0   1]]


In [ ]:
print(np.einsum("ij->ji",A))

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]
 [ 1  1  1]]


In [ ]:
A = np.array([[2,6,5,2,1],
              [2,-2,2,3,1],
               [1,5,4,0,1]
])
B = np.array([[[2,6,5,2,1],
              [2,-2,2,3,1],
               [1,5,4,0,1],
               [1,5,4,0,1],
               [1,5,4,0,1]],
                [[2,6,5,2,1],
              [2,-2,2,3,1],
               [1,5,4,0,1],
                 [1,5,4,0,1],
                 [1,5,4,0,1]]
])
print(np.sum(A,axis=0))
print(np.einsum("ij -> j",A))

[ 5  9 11  5  3]
[ 5  9 11  5  3]


In [ ]:
# Q = batchsize, s_q, modelsize
# K = batchsize, s_k, modelsize
Q = np.random.randn(32, 64, 512)
K = np.random.randn(32, 128, 512)
np.einsum("bqm,bkm-> bqk",Q,K).shape


(32, 64, 128)

In [ ]:
A = np.random.randn(2,4,4,2) # bcij
B = np.random.randn(2,4,4,1) # bcik
np.einsum("bcik,bcij -> bckj",B,A).shape

(2, 4, 1, 2)

In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]],
    [[1,2,0],
    [3,5,1]]
])
print(tensor_three_d.shape)
x_s = tf.expand_dims(tensor_three_d, axis=3)
print(x_s.shape)


(4, 2, 3)
(4, 2, 3, 1)


In [ ]:
x = tf.constant([2,3,4,5])
print(x.shape)
x_expnanded = (tf.expand_dims(x,axis=0))
x_squeezed = tf.squeeze(x_expnanded, axis=0)
print(x_squeezed)

(4,)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
t1 = [[1, 2, 3,5],
      [4, 5, 6,5]]
print(tf.reshape(t1,[2,-1]))

tf.Tensor(
[[1 2 3 5]
 [4 5 6 5]], shape=(2, 4), dtype=int32)


In [ ]:
t1 = [[[1, 2, 3], [4, 5, 6]]]
t2 = [[[7, 8, 9], [10, 11, 12]]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)
tf.concat([t1, t2], 0)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tf.stack([t1,t2], axis = 0)

<tf.Tensor: shape=(2, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [ ]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 5,], [2, 3]])
tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
tf.gather(params, [0,3,5])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p3', b'p5'], dtype=object)>

In [ ]:
params = tf.constant([[[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]]])
tf.gather(params, [0,2], axis=1)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [20., 21., 22.]]], dtype=float32)>

In [ ]:
indices = [[0,1],[1,0]]
params = [[['a0', 'b0'], ['c0', 'd0']],
              [['a1', 'b1'], ['c1', 'd1']]]
tf.gather_nd(params,indices,batch_dims=1)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b0', b'c1'], dtype=object)>

In [ ]:
tensor_two_d = [[1,2,0],
                           [3,],
                           [1,5,6,5,6],
                           [2,3]]
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [ ]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values=[11,56], dense_shape=[5,6]
)

In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [ ]:
tensor_string = tf.constant(["Hello","I am","a string"])
print(tensor_string)

tf.Tensor([b'Hello' b'I am' b'a string'], shape=(3,), dtype=string)


In [ ]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello+I am+a string'>

In [ ]:
x = tf.constant([1,2])
x_var = tf.Variable(x , name = "Var1")
print(x_var)

<tf.Variable 'Var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [ ]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0], dtype=int32)>

In [ ]:
with tf.device('CPU:0'):
  x_var = tf.Variable(0.2)
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])
with tf.device('TPU:0'):
  x_3 = x_1+x_2
print(x_1)
print(x_2)
print(x_3)


tf.Tensor([1 3 4], shape=(3,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([2 4 5], shape=(3,), dtype=int32)
